pyExceptions/__init__.py,sha256=1zfnZL5tJFwhGXdne8vvYiVTKt1jqClTEimN13yb878,3042
pyExceptions-0.1.8.dist-info/LICENSE.md,sha256=DF4r-Jbsz_ZASY4VjV0ZZVaaHYkH9a20BkVExpq8doE,10571
pyExceptions-0.1.8.dist-info/METADATA,sha256=6o9G61VLp64igZ2osK_8mcj3M7PvNfQBs4YTXg7BARY,2080
pyExceptions-0.1.8.dist-info/WHEEL,sha256=p46_5Uhzqz6AzeSosiOnxK-zmFja1i22CrQCjmYe8ec,92
pyExceptions-0.1.8.dist-info/top_level.txt,sha256=FCUx2KjHbxV3j3LdKBNNoUArrjEkFQTn9tzdqg_RCWs,13
pyExceptions-0.1.8.dist-info/RECORD,,
