pyExceptions/__init__.py,sha256=ApGIyO30b9klim4h6BRdFpUw--S2-k-Us6IFK_MJrG4,3018
pyExceptions-0.1.0.dist-info/LICENSE.md,sha256=DF4r-Jbsz_ZASY4VjV0ZZVaaHYkH9a20BkVExpq8doE,10571
pyExceptions-0.1.0.dist-info/METADATA,sha256=f3_b_kDpJ8hEneWCFEhO1lRpXNaI0AcABeg0nYkoqhk,1558
pyExceptions-0.1.0.dist-info/WHEEL,sha256=p46_5Uhzqz6AzeSosiOnxK-zmFja1i22CrQCjmYe8ec,92
pyExceptions-0.1.0.dist-info/top_level.txt,sha256=FCUx2KjHbxV3j3LdKBNNoUArrjEkFQTn9tzdqg_RCWs,13
pyExceptions-0.1.0.dist-info/RECORD,,
