pyExceptions/__init__.py,sha256=FLfjzJxs10wB8owzOMtfhqFxjhIjobwHrYdflltdfvk,2997
pyExceptions-0.1.3.dist-info/LICENSE.md,sha256=DF4r-Jbsz_ZASY4VjV0ZZVaaHYkH9a20BkVExpq8doE,10571
pyExceptions-0.1.3.dist-info/METADATA,sha256=7K0F5OXrBpeNafIX8mH4wArPhr-lX4zTReaB8pVJfus,1808
pyExceptions-0.1.3.dist-info/WHEEL,sha256=p46_5Uhzqz6AzeSosiOnxK-zmFja1i22CrQCjmYe8ec,92
pyExceptions-0.1.3.dist-info/top_level.txt,sha256=FCUx2KjHbxV3j3LdKBNNoUArrjEkFQTn9tzdqg_RCWs,13
pyExceptions-0.1.3.dist-info/RECORD,,
